version: "3"
services:
  postgres:
    container_name: postgres_t2
    image: postgres:14-alpine
    env_file:
      - backend/.env
    expose:
      - "5445"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    command: -p 5445



  api:
    container_name: djangoapp_t2
    build:
      context: ./backend
    expose:
      - 8002
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8002
    volumes:
      - static_root:/backend/static/
      - media_storage:/backend/media/
    depends_on:
      - postgres
    restart: always


  nginx:
    build: ./nginx
    ports:
      - "8016:8016"
    depends_on:
      - api
    volumes:
      - static_root:/backend/static/
      - media_storage:/backend/media/



  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api




volumes:
  postgres_data:
  static_root:
  media_storage:



