version: "3"
services:
  postgres:
    container_name: postgres_t2
    image: postgres:14-alpine
    env_file:
      - backend/.env
    ports:
      - "5445:5445"
    expose:
      - "5445"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data/
    restart: always
    command: -p 5445

  api:
    container_name: djangoapp_t2
    build:
      context: ./backend
    ports:
      - "8002:8002"
    command: python manage.py runserver 0.0.0.0:8002
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - api
