# Generated by Django 4.2.4 on 2023-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('address_ru', models.CharField(max_length=255, null=True)),
                ('address_en', models.CharField(max_length=255, null=True)),
                ('address_ky', models.CharField(max_length=255, null=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('first_name_ru', models.CharField(max_length=255, null=True)),
                ('first_name_en', models.CharField(max_length=255, null=True)),
                ('first_name_ky', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('last_name_ru', models.CharField(max_length=255, null=True)),
                ('last_name_en', models.CharField(max_length=255, null=True)),
                ('last_name_ky', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255, null=True)),
                ('position_en', models.CharField(max_length=255, null=True)),
                ('position_ky', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, default='/default_employee.jpg', null=True, upload_to='')),
                ('is_visible', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ky', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=255)),
                ('customer_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_en', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_ky', models.CharField(blank=True, max_length=255, null=True)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
