# Generated by Django 4.2.4 on 2023-09-04 17:04

import content.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('city_ru', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('city_en', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('city_ky', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('image', models.ImageField(blank=True, null=True, upload_to=content.models.address_images, verbose_name='Картинка')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='BigTextualContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_title', models.CharField(max_length=100, verbose_name='Надзаголовок')),
                ('pre_title_ru', models.CharField(max_length=100, null=True, verbose_name='Надзаголовок')),
                ('pre_title_en', models.CharField(max_length=100, null=True, verbose_name='Надзаголовок')),
                ('pre_title_ky', models.CharField(max_length=100, null=True, verbose_name='Надзаголовок')),
                ('pre_title_image', models.ImageField(upload_to=content.models.textual_pre_title, verbose_name='Картинка надзаголовка')),
                ('title', models.CharField(default='No title provided', max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(default='No title provided', max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(default='No title provided', max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(default='No title provided', max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to=content.models.textual_content, verbose_name='Общая картинка')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
            ],
            options={
                'verbose_name': 'Текстовый контент',
                'verbose_name_plural': 'Текстовый контент',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('first_name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('first_name_en', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('first_name_ky', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('last_name_ru', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('last_name_en', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('last_name_ky', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, null=True, upload_to=content.models.employee_images, verbose_name='Фото')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='OurValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=content.models.values_photos, verbose_name='Картинка')),
                ('name', models.CharField(max_length=255, verbose_name='Ценность')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Ценность')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Ценность')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Ценность')),
                ('description', models.TextField(blank=True, default='No description provided', verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, default='No description provided', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, default='No description provided', null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, default='No description provided', null=True, verbose_name='Описание')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
            ],
            options={
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('customer', models.CharField(blank=True, max_length=255, verbose_name='Заказчик')),
                ('customer_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказчик')),
                ('customer_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказчик')),
                ('customer_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заказчик')),
                ('image', models.ImageField(blank=True, null=True, upload_to=content.models.project_images, verbose_name='Картинка')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='SummaryNumericData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_description', models.CharField(max_length=255, verbose_name='Описание данных')),
                ('data_description_ru', models.CharField(max_length=255, null=True, verbose_name='Описание данных')),
                ('data_description_en', models.CharField(max_length=255, null=True, verbose_name='Описание данных')),
                ('data_description_ky', models.CharField(max_length=255, null=True, verbose_name='Описание данных')),
                ('color', models.SlugField(choices=[('38E55E', 'Зеленый'), ('FFDC60', 'Желтый'), ('5956E8', 'Синий'), ('F96A4B', 'Оранжевый'), ('F5B7FF', 'Розовый'), ('CA87FF', 'Фиолетовый')], default='38E55E', verbose_name='Цвет')),
                ('number', models.IntegerField(default=0, verbose_name='Число')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
            ],
            options={
                'verbose_name': 'Суммарные данные',
                'verbose_name_plural': 'Суммарные данные',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тег')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Тег')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Тег')),
                ('title_ky', models.CharField(max_length=100, null=True, verbose_name='Тег')),
                ('description', models.TextField(blank=True, verbose_name='Описание тега')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание тега')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание тега')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание тега')),
                ('image', models.ImageField(upload_to=content.models.textual_tags, verbose_name='Иконка тега')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
                ('related_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='content.bigtextualcontent', verbose_name='Текстовый объект')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='PhoneContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.addresscontact')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='EmailContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_visible', models.BooleanField(default=False, verbose_name='Виден на сайте')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.addresscontact')),
            ],
            options={
                'verbose_name': 'Email контакт',
                'verbose_name_plural': 'Email контакты',
            },
        ),
    ]
