# Generated by Django 4.2.4 on 2023-08-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('address_ru', models.CharField(blank=True, null=True)),
                ('address_en', models.CharField(blank=True, null=True)),
                ('address_kg', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_ru', models.CharField()),
                ('last_name_ru', models.CharField()),
                ('position_ru', models.CharField()),
                ('first_name_en', models.CharField(blank=True, null=True)),
                ('last_name_en', models.CharField(blank=True, null=True)),
                ('position_en', models.CharField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField()),
                ('description_ru', models.CharField()),
                ('customer_ru', models.CharField()),
                ('name_en', models.CharField(blank=True, null=True)),
                ('description_en', models.CharField(blank=True, null=True)),
                ('customer_en', models.CharField(blank=True, null=True)),
                ('name_kg', models.CharField(blank=True, null=True)),
                ('description_kg', models.CharField(blank=True, null=True)),
                ('customer_kg', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
