# Generated by Django 4.2.4 on 2023-09-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='/default_employee.jpg', null=True, upload_to='employee_images'),
        ),
    ]
