# Generated by Django 4.2.4 on 2023-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarynumericdata',
            name='color',
            field=models.SlugField(choices=[('053B50', 'Синий'), ('A73121', 'Красный')], default='Красный', verbose_name='Цвет'),
        ),
    ]
