# Generated by Django 4.2.4 on 2023-09-01 15:48

from .. import models as m
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_addresscontact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigTextualContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=m.textual_content)),
                ('title', models.CharField(blank=True, default='No title provided', max_length=255)),
                ('title_ru', models.CharField(blank=True, default='No title provided', max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, default='No title provided', max_length=255, null=True)),
                ('title_ky', models.CharField(blank=True, default='No title provided', max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('tags', models.CharField(max_length=100)),
                ('tags_ru', models.CharField(max_length=100, null=True)),
                ('tags_en', models.CharField(max_length=100, null=True)),
                ('tags_ky', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Текстовый контент',
                'verbose_name_plural': 'Текстовый контент',
            },
        ),
        migrations.CreateModel(
            name='OurValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=m.values_photos)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ky', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='No description provided')),
                ('description_ru', models.TextField(blank=True, default='No description provided', null=True)),
                ('description_en', models.TextField(blank=True, default='No description provided', null=True)),
                ('description_ky', models.TextField(blank=True, default='No description provided', null=True)),
            ],
            options={
                'verbose_name': 'Ценность',
                'verbose_name_plural': 'Ценности',
            },
        ),
        migrations.CreateModel(
            name='SummaryNumericData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('data_description', models.CharField(max_length=255)),
                ('data_description_ru', models.CharField(max_length=255, null=True)),
                ('data_description_en', models.CharField(max_length=255, null=True)),
                ('data_description_ky', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Суммарные данные',
                'verbose_name_plural': 'Суммарные данные',
            },
        ),
    ]
